name: qsr_flutter_app
description: A Flutter app for Quick Service Restaurants to manage orders and connect to Bluetooth printers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Google Services
  google_sign_in: ^6.1.5
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.0
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # Bluetooth & Printing
  # flutter_bluetooth_serial: ^0.4.0  # Temporarily disabled for Android compatibility
  esc_pos_utils: ^1.1.0
  # thermal_printer: ^0.1.4  # Will implement later with proper Bluetooth package
  # permission_handler: ^11.0.1  # Will implement later when needed
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  
  # UI Components
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.0
  
  # Charts & Analytics
  fl_chart: ^0.64.0
  
  # Network & Connectivity
  connectivity_plus: ^5.0.1
  url_launcher: ^6.2.1
  http: ^1.1.0
  
  # PDF Generation & Sharing
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/templates/kot_template.txt
    - assets/fonts/
    - assets/translations/
    - assets/images/